docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - Routing: routing.md
site_name: laminas-router
site_description: 'laminas-router: Flexible routing system for HTTP and console applications'
repo_url: 'https://github.com/laminas/laminas-router'
